### ISSUE TITLE
Set SO_REUSEADDR socket option in TCPServer

### ISSUE THREAD

**Issue by yateya** [Zenol/sednl#1]
TCPServer doesn't set the socket reuse flag. So when server application crash (or closed forcefully) I can't listen for the same port for some time.

int option_reuse = 1;
int errcode = setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, (const char *)&option_reuse, sizeof(option_reuse));
if (errcode == -1)
       continue;

**Comment by Zenol** [comment]
Thanks for the feed back. It will be fixed tomorow.

**Comment by Zenol** [comment]
The feature should be added. Since it break the ABI, it will be in the next release. You have to manually (see TCPServer) set the flag on, since activating it by default can be considered as a security issue.
